bot:
  server: telegram
  token_env: TG_TOKEN
youtube:
  api_key_env: YOUTUBE_API
  heavy_pool_size: 20
  light_pool_size: 40
storage:
  q_size: 300
  storages:
    - db1:
        cls: DropBox
        storage_time: 4
        refresh_token_env: DROPBOX_REFRESH_TOKEN
        app_key_env: DROPBOX_APP_KEY
        app_secret_env: DROPBOX_APP_SECRET
    - db2:
        cls: DropBox
        storage_time: 4
        refresh_token_env: DROPBOX_REFRESH_TOKEN_2
        app_key_env: DROPBOX_APP_KEY_2
        app_secret_env: DROPBOX_APP_SECRET_2
grpc:
  host: "5.35.115.35"
  port: 50051
  channel_idle_time: 15
